#!/bin/bash
set -e

echo "======================================"
echo "Proton VPN Setup for NexusLB v3"
echo "======================================"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

# Detect OS
OS=$(lsb_release -si 2>/dev/null || echo "Unknown")
echo "Detected OS: $OS"

# Step 1: Install required packages
echo ""
echo "[1/6] Installing required packages..."
apt-get update
apt-get install -y curl wget openvpn iptables-persistent

# Step 2: Download Proton VPN configuration
echo ""
echo "[2/6] Downloading Proton VPN configuration..."

# Create VPN config directory
mkdir -p /etc/openvpn/protonvpn
cd /etc/openvpn/protonvpn

# Download free server configurations
# Note: You may need to manually download these from Proton VPN website
# https://protonvpn.com/free-vpn
echo "Downloading Netherlands free config..."
wget -q "https://protonvpn.com/download/config/nl-free.ovpn" -O nl-free.ovpn || {
    echo "Failed to download. Please manually download from:"
    echo "https://protonvpn.com/free-vpn"
}

echo "Downloading US free config..."
wget -q "https://protonvpn.com/download/config/us-free.ovpn" -O us-free.ovpn || echo "US config download failed"

echo "Downloading Japan free config..."
wget -q "https://protonvpn.com/download/config/jp-free.ovpn" -O jp-free.ovpn || echo "Japan config download failed"

# Step 3: Create credentials file
echo ""
echo "[3/6] Setting up credentials..."

if [ -z "$VPN_USER" ]; then
    read -p "Enter Proton VPN username: " VPN_USER
fi
if [ -z "$VPN_PASS" ]; then
    read -s -p "Enter Proton VPN password: " VPN_PASS
fi
echo ""

# Create auth file
cat > /etc/openvpn/protonvpn/auth.txt << EOF
$VPN_USER
$VPN_PASS
EOF

chmod 600 /etc/openvpn/protonvpn/auth.txt

# Step 4: Update OpenVPN configs to use auth file
echo ""
echo "[4/6] Configuring OpenVPN..."

for config in *.ovpn; do
    if [ -f "$config" ]; then
        # Replace auth-user-pass with auth file
        sed -i 's|auth-user-pass|auth-user-pass /etc/openvpn/protonvpn/auth.txt|g' "$config"
        # Add route-nopull to allow manual routing (optional)
        # echo "route-nopull" >> "$config"
    fi
done

# Step 5: Create VPN management script
echo ""
echo "[5/6] Creating management scripts..."

cat > /usr/local/bin/vpnctl << 'EOF'
#!/bin/bash
VPN_DIR="/etc/openvpn/protonvpn"

case "$1" in
    start)
        echo "Starting Proton VPN..."
        SERVER="${2:-nl}"
        if [ "$SERVER" = "nl" ]; then
            CONFIG="$VPN_DIR/nl-free.ovpn"
        elif [ "$SERVER" = "us" ]; then
            CONFIG="$VPN_DIR/us-free.ovpn"
        elif [ "$SERVER" = "jp" ]; then
            CONFIG="$VPN_DIR/jp-free.ovpn"
        else
            echo "Unknown server: $SERVER"
            echo "Usage: vpnctl start [nl|us|jp]"
            exit 1
        fi
        
        if [ ! -f "$CONFIG" ]; then
            echo "Config not found: $CONFIG"
            exit 1
        fi
        
        openvpn --config "$CONFIG" --daemon
        sleep 5
        echo "VPN started. Checking connection..."
        curl ifconfig.co
        ;;
    stop)
        echo "Stopping Proton VPN..."
        pkill -f "openvpn.*protonvpn"
        ;;
    status)
        if pgrep -f "openvpn.*protonvpn" > /dev/null; then
            echo "VPN is running"
            curl ifconfig.co
        else
            echo "VPN is not running"
        fi
        ;;
    restart)
        $0 stop
        sleep 2
        $0 start $2
        ;;
    *)
        echo "Usage: vpnctl [start|stop|status|restart] [nl|us|jp]"
        exit 1
        ;;
esac
EOF

chmod +x /usr/local/bin/vpnctl

# Step 6: Setup firewall rules
echo ""
echo "[6/6] Setting up firewall rules..."

# Create iptables rules for kill switch
cat > /etc/iptables/rules.v4 << 'EOF'
# Generated by iptables-save v1.8.4 on $(date)
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -i tun+ -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT
-A INPUT -j DROP
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
-A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A OUTPUT -p udp --dport 1194 -j ACCEPT
-A OUTPUT -j DROP
COMMIT
EOF

echo ""
echo "======================================"
echo "Installation complete!"
echo "======================================"
echo ""
echo "Next steps:"
echo "1. Make sure UDP port 1194 is open in Azure NSG"
echo "2. Start VPN: sudo vpnctl start nl"
echo "3. Check status: sudo vpnctl status"
echo "4. Test connection: curl ifconfig.co"
echo ""
echo "To route only upstream traffic through VPN,"
echo "see /etc/openvpn/protonvpn/split-routing.sh"
